import Head from "next/head";
import React from "react";

function PlaylistPage() {
	return (
		<>
			<Head key="111">
				<title>Podcast-Playlists</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>PlaylistPage</div>
		</>
	);
}

export default PlaylistPage;
