import Head from "next/head";
import React from "react";

function SearchPage() {
	// ======search=====================

	// searchForTerm(term:"Billy Graham", filterForTypes:[PODCASTSERIES]){
	// 	searchId
	// 	podcastSeries{
	// 	  uuid
	// 	  name
	// 	  rssUrl
	// 	}
	// 	podcastEpisodes{
	// 	  uuid
	// 	  name
	// 	  audioUrl
	// 	}
	//   }

	// getMultiplePodcastSeries(uuids:[

	// ];){
	// 	uuid
	// 	name
	// 	itunesId
	// 	description
	// 	imageUrl
	// 	itunesInfo{
	// 	  uuid
	// 	  publisherName
	// 	}
	//   }
	// ===========end of search=====================

	return (
		<>
			<Head key="111">
				<title>Podcast-Search</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="mx-auto mt-3 h-fit max-w-[350px]">
				<input
					type="text"
					placeholder="Search Podcast..."
					className=" mx-auto w-full rounded-md border-2 border-[#6041b6] bg-transparent p-1 text-white outline-1 outline-[white] placeholder:pl-2 placeholder:text-sm placeholder:text-[#6d6a6a]"
				/>
			</div>
		</>
	);
}

export default SearchPage;
